version: '3.8'

services:
  web:
    build: ./Walid-Ayaan-Kawsar-main
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn Portfolio.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - ./Walid-Ayaan-Kawsar-main/static:/app/static
      - ./Walid-Ayaan-Kawsar-main/Media:/app/Media  #  Media volume
    expose:
      - "8000"
    env_file: 
      - ./Walid-Ayaan-Kawsar-main/.env
    environment:
      - DJANGO_SETTINGS_MODULE=Portfolio.settings
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Walid-Ayaan-Kawsar-main/static:/app/static
      - ./Walid-Ayaan-Kawsar-main/Media:/app/Media  # âœ… Media volume
    depends_on:
      - web
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    restart: always
